meta_parameters:
  dummy_value: true

leader:
  RobotLeaderNode:
    ros__parameters:
      root_config:
        # Override this to use a real robot
        robot_protocol: DummyBouncingRobot
        move_speed: 0.0  # Doesn't affect the 'leader', since it doesn't get write cmds

follower:
  RobotFollowerNode:
    ros__parameters:
      root_config:
        # Override this to use a real robot
        robot_protocol: DummyCopycatRobot
        move_speed: 0.35

