meta_parameters:
  dummy_value: true

leader:
  RobotLeaderNode:
    ros__parameters:
      root_config:
        # Override this to use a real robot
        robot_protocol: DummyBouncingRobot
        move_speed: 0.0

follower:
  RobotFollowerNode:
    ros__parameters:
      root_config:
        # Override this to use a real robot
        robot_protocol: DummyCopycatRobot
        move_speed: 20.0

