[tool.poetry]
name = "myarm_ai"
version = "0.1.0"
description = "This is my MyArm package for controlling the MyArm M&C elephant robotics arms using ROS2"
authors = ["apockill <apocthiel@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.12.0,<3.13"
acton-ai = "^0.3.0"
pydantic = "^2.10.3"
lerobot = {git = "https://github.com/huggingface/lerobot.git", rev="59e2757"}

[tool.poetry.scripts]
# Each entry here will create an executable which can be referenced in launchfiles
follower_robot = "myarm_ai.nodes.follower_robot:main"
leader_robot = "myarm_ai.nodes.leader_robot:main"
convert_isaac_to_lerobot = "myarm_ai.scripts.convert_isaac_to_lerobot:main"

[tool.colcon-poetry-ros.data-files]
"share/ament_index/resource_index/packages" = ["resource/myarm_ai"]
"share/myarm_ai" = ["package.xml", "urdfs/"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"