meta_parameters:
  urdf_modules_to_load:
    # URDF's are attached to base_link down below in the
    - namespace: "follower"
      urdf_constant_name: "myarm_m"
      apply_namespace_to_urdf: false
    - namespace: "leader"
      urdf_constant_name: "myarm_c"
      apply_namespace_to_urdf: false

leader:
  RobotLeaderNode:
    ros__parameters:
      root_config:
        test_val: true

follower:
  RobotFollowerNode:
    ros__parameters:
      root_config:
        test_val: true

urdf_arrangement:
  interactive_transform_publisher:
    ros__parameters:
      static_transforms_file: /robot/persistent/interactive_transforms.json
      scale_factor: 1.0
      tf_publish_frequency: 1.0
      transforms:
        # Mounts the URDFs to the world so they can be visualized
        - "base_link:follower_base"
        - "base_link:leader_base"