meta_parameters:
  urdf_modules_to_load:
    # URDF's are attached to base_link down below in the
    - namespace: "myarm_m"
      urdf_constant_name: "myarm_m"
    - namespace: "myarm_c"
      urdf_constant_name: "myarm_c"


example_node_namespace:
  MyArmNode:
    ros__parameters:
      root_config:
        forklift_speed: 0.25
        forklift_max_extent: 0.5

urdf_arrangement:
  interactive_transform_publisher:
    ros__parameters:
      static_transforms_file: /robot/persistent/interactive_transforms.json
      scale_factor: 1.0
      tf_publish_frequency: 1.0
      transforms:
        # Mounts the URDFs to the world so they can be visualized
        - "base_link:myarm_m.base"
        - "base_link:myarm_c.base"